# Tomcat
server:
  port: 9000

# Spring
spring:
  application:
    # 应用名称
    name: test-oauth2
  profiles:
    # 环境配置
    active: prod
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    # 连接池中的最小空闲连接 默认 0, 修改为1
    lettuce:
      pool:
        min-idle: 1
